import path from "node:path";

export interface FormatOptions {
  projectName: string;
  fileTree: string;
  files: { path: string; content: string }[];
  totalTokens: number;
}

/**
 * Maps file extensions to fenced code block language identifiers.
 * Extensions are lowercase and without the leading dot.
 */
const LANGUAGE_MAP: Record<string, string> = {
  ts: "typescript",
  tsx: "tsx",
  js: "javascript",
  jsx: "jsx",
  mjs: "javascript",
  cjs: "javascript",
  py: "python",
  rs: "rust",
  go: "go",
  rb: "ruby",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  swift: "swift",
  c: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  h: "c",
  hpp: "cpp",
  cs: "csharp",
  php: "php",
  lua: "lua",
  r: "r",
  json: "json",
  jsonc: "jsonc",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  md: "markdown",
  mdx: "mdx",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  sql: "sql",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  fish: "fish",
  xml: "xml",
  svg: "xml",
  graphql: "graphql",
  gql: "graphql",
  prisma: "prisma",
  env: "dotenv",
  dockerfile: "dockerfile",
  makefile: "makefile",
  mk: "makefile",
  tf: "hcl",
  tfvars: "hcl",
  hcl: "hcl",
  proto: "protobuf",
  vue: "vue",
  svelte: "svelte",
};

/**
 * Returns the fenced code block language identifier for a given file path.
 * Falls back to empty string (plain fenced block) for unknown extensions.
 */
export function getLanguageId(filePath: string): string {
  const base = path.basename(filePath).toLowerCase();

  // Handle extensionless filenames that are well-known (e.g. Dockerfile, Makefile)
  if (base === "dockerfile") return "dockerfile";
  if (base === "makefile" || base === "gnumakefile") return "makefile";
  if (base === ".env" || base.startsWith(".env.")) return "dotenv";

  const ext = path.extname(filePath).replace(/^\./, "").toLowerCase();
  return LANGUAGE_MAP[ext] ?? "";
}

/**
 * Renders a single file section: heading + fenced code block.
 */
function renderFileSection(file: { path: string; content: string }): string {
  const lang = getLanguageId(file.path);
  return `## ${file.path}\n\`\`\`${lang}\n${file.content}\n\`\`\``;
}

/**
 * Builds the complete markdown output string from the provided options.
 */
export function formatOutput(options: FormatOptions): string {
  const { projectName, fileTree, files, totalTokens } = options;

  const header = [
    `# Repository: ${projectName}`,
    `Generated by repopack | ${files.length} files | ~${totalTokens} tokens`,
  ].join("\n");

  const treeSection = `## File Tree\n\`\`\`\n${fileTree}\n\`\`\``;

  const fileSections = files.map(renderFileSection).join("\n\n");

  return [header, treeSection, fileSections].join("\n\n");
}
